### ISSUE TITLE
IsNullOr()

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#114]
Validation for optional arguments, it'd be nice to have a way to say 'validate, but only if supplied'

## Today:
```C#
if (arg != null) {
  EnsureArg.Matches(arg, new Regex(@"^\d*$"), nameof(arg));
}
```

## Proposed syntax
(I'm not sure how to do this nicely with EnsureArg - and therefore it might belong in a sister library and NOT here) :
```C#
Ensure.That(arg, nameof(arg)).IsNullOr().Matches(new Regex(@"^\d*$"));
```

_Since this is more of a feature-suggestion to myself, feel free to close it if you don't want the noise of me tracking ideas on this backlog :)_

**Comment by danielwertheim** [comment]
The "today" case, wouldn't that e.g. be:

```csharp
EnsureArg.IsNotNull(arg, nameof(arg));
EnsureArg.Matches(arg, new Regex(@"^\d*$"), nameof(arg));
```

Anyway, the API of `Ensure.That(...)` was like that at one point, as in it returned the `Param` so that more rules could be chained. Wasn't there a performance reason that it was removed?

**Comment by ndrwrbgs** [comment]
In this case, no, it's that the input is { not supplied || valid } so null _is_ okay in this case. Like the user can not supply a phone number, but if they do, it should be a phone number.

I'm sure there was a performance problem :-P - I'll deal with performance before sending any PRs but I think it's worth looking into :-)

**Comment by ndrwrbgs** [comment]
+1 on having this requirement again - nullable (optional arguments) that have constraints IFF supplied.
