### ISSUE TITLE
Suggestion: Adds a way to verify if an enum value is defined

### ISSUE THREAD

**Issue by maartenoosterhoff** [danielwertheim/Ensure.That#117]
Hi,

I want to make sure that the enum-values are defined. Some thing like:

```
class MyClass {
    public MyClass(SomeEnum someEnum) {
        EnsureArg.IsDefined(someEnum, nameof(someEnum));
    }
}

enum SomeEnum { Valid }

// Passes
new MyClass(SomeEnum.Valid);

// Fails
var invalidEnum = (SomeEnum)-1;
new MyClass(invalidEnum);
```

**Comment by danielwertheim** [comment]
@maartenoosterhoff Are you interested in providing a PR for this?

**Comment by dmarciano** [comment]
@danielwertheim Good afternoon.  I just came across this project while exploring GitHub and found it very interesting and would like to contribute.  I figured this issue was a simple one I could start with as I familiarize myself more with this library.  I just wanted to check if this is still something that you were interested in implementing before I started work on it.

**Comment by maartenoosterhoff** [comment]
@danielwertheim Sorry for the late reply, but unfortunately I do not have the time to do this at the moment.
Fortunately @dmarciano is just on time to crack it 👍

**Comment by danielwertheim** [comment]
@dmarciano absolutely

**Comment by ndrwrbgs** [comment]
@dmarciano Won't matter as far as the public-facing API, so feel free to get in an MVP of this first, but from perf work in C# I know that enums use some slow reflection to do the kinds of things we'll need to do here. We have some guidance at work about it, but it essentially boils down to caching the `.GetValues()` call on the enum type.

That said, I'd be cautious about caching things for users based on generic types passed in, so I'd probably personally have a `bool useCache = true` flag, that most users could omit (and get performant code) but gives an escape hatch to folks as needed.

**Comment by danielwertheim** [comment]
@ndrwrbgs Why not cache?

**Comment by ndrwrbgs** [comment]
It's _really_ pedantic and just "covering our butts" for scenarios I don't claim to fully understand, but I am imagining a scenario that reflection is being used to construct enums at runtime. These being passed into a generic method that calls us would result in unbounded memory growth if we cache everything.

That said, it's fully possible that .NET would internally result in the same memory growth, and to be concerned about _us_ in the scenario would just be silly; but thoughts are if we can (_very_ easily) supply an (optional) flag to shut it off then we would never have to "panic-release-a-fix" if something were wrong (or have someone internal in a big company have to defend the library). At that point it becomes a user-facing fix (just pass `false`)

**Comment by ndrwrbgs** [comment]
working on this

**Comment by danielwertheim** [comment]
@ndrwrbgs thanks for the PR. Do you feel that it should be released immediately or do you want to address more stuff?

**Comment by ndrwrbgs** [comment]
I still want the read-only changes from December out so sooner is better
for me :P but I'm sure I'll have some more minor version changes upcoming
now that I'm back at it (read: Seattle has sun again).
