### ISSUE TITLE
Support new nullable C#8 attributes

### ISSUE THREAD

**Issue by roryprimrose** [danielwertheim/Ensure.That#118]
From what I understand, the new nullable attributes could be put into Ensure.That to help with nullable analysis in calling code. Something like https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/#nullness-dependence-between-inputs-and-outputs-notnullifnotnullstring for example.

This would mean that any analysis of code that comes after a call to Ensure.Any.IsNotNull (or similar functions) will identify that the parameter checked cannot be null after the Ensure call.

**Comment by roryprimrose** [comment]
Hmm, just read that the NotNullIfNotNull attribute only applies to method return values or ref parameters. :(

**Comment by ndrwrbgs** [comment]
I'd probably leave this open -- if these are finally coming into the base language, we could replace the ReSharper annotations for the same with the other annotations. It might not give the signal we are wanting on IsNotNull (duplicate of #122) but for all other cases (like paramName shouldn't be null if supplied) it would provide the R# experience to folks w/o R# (if https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes is integrated into the IDE well)

**Comment by ndrwrbgs** [comment]
I'd probably wait about 4 months before bothering, to see if it reaches critical mass, but I'd still want to move to something more 'official' (which is probably why those were introduced?)

**Comment by danielwertheim** [comment]
@ndrwrbgs reopen or?

**Comment by ndrwrbgs** [comment]
I'll keep it in my email inbox, so we can leave this here for now

**Comment by ndrwrbgs** [comment]
@roryprimrose do you know of any analysis took that uses these today? Encountered the new attributes myself in netcoreapp30 but not sure if the IDE is doing anything with them yet.

If there is something using them, we can easily add them everywhere the R# ones are. If not I'd defer again.

**Comment by ndrwrbgs** [comment]
Based on https://www.google.com/url?sa=t&source=web&rct=j&url=https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes&ved=2ahUKEwjq7bmKmebnAhWHJDQIHSfRCA8QFjABegQIBhAL&usg=AOvVaw0InQ5tpB5sa5w06SmH9mX1&cshid=1582410200057, projects using nullable types might require this to get any benefit out of Ensure.That.

I'm a bit work-tired now so I'll test that theory in the future, unless someone else beats me to it ;-)

**Comment by ndrwrbgs** [comment]
It looks like it doesn't _break_ the build, but can throw compiler warnings. We would be able to pretty easily annotate nullability on the EnsureArg/Ensure.Type methods, but Ensure.That is a bit too complex for the trivial conditions implemented from what I see in:

https://www.meziantou.net/csharp-8-nullable-reference-types.htm#post-condition-attri

But that's no reason not to support it for the other APIs!

**Comment by ndrwrbgs** [comment]
Options for Ensure.That API: `IsNotNull` returns the input value. User can use the `!` symbol to tell the compiler that the value is really really not null after the call.
@danielwertheim could you reopen this now? I'll take a look at adding the attributes.

**Comment by roryprimrose** [comment]
One thing to consider with compiler warnings is where people turn on TreatWarningsAsErrors. That would then fail their builds.

**Comment by ndrwrbgs** [comment]
^ that's why I'm taking the task :)

**Comment by roryprimrose** [comment]
Sorry, I misunderstood your comment :)

**Comment by ndrwrbgs** [comment]
I tried to pick this up today, but it's complicated by the C#8 analysis only going one-layer-deep and only looking at flat inputs/outputs, whereas we wrap the input (for various language reasons that I don't yet think are invalidated by this case) in the `Param` struct.

This suggests we could never (in the Static Analysis's current functionality, which leaves a lot to be desired :( the competition to C#8's SA is already further, provide us with a good solution .NET!) handle Ensure.That(arg).IsNotNull() how we would optimally desire.

Oddly, without any modification (actually even with remove our existing `ContractAnnotations` [.NET standard that got, sadly, seemingly, orphaned by the team] and the R# NotNull) arg = EnsureArg.IsNotNull(arg) doesn't warn (I tried everything I could to make it notice "hey I haven't said this actually returns not null, do you care?" and couldn't).

I'm open to revisit this but a direct use case to work off would help to expedite "yeah this is totally impossible" or "ohhh here's the solution" resolution.

Recommendation: @roryprimrose supply an example (if you can remember it, so sorry for the COVID induced latency and totally understandable if you've forgotten this completely :)) you'd like to see work, or @danielwertheim re-close the issue for now.

Recommendation for User96725416 in 2026: `arg = EnsureArg.IsNotNull(arg)` seems to (incorrectly and concerningly :-P) hide the error, but I'd suggest you #nullable disable perhaps instead as I could've validate the aforementioned work around is actually validating _anything_ and I'd rather you not accidentally get a false positive from something like Ensure.IsNull() being assumed by .NET to mean notnull
