### ISSUE TITLE
IsNotNull does not suppress CA1062

### ISSUE THREAD

**Issue by rsobon** [danielwertheim/Ensure.That#122]
Using IsNotNull should get rid if the [CA1062 warning](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019) generated by the latest stable version of Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.7:

```
Ensure.That(arg).IsNotNull();
```

Even though there seems to be `[ValidatedNotNull]` attribute on the `EnsureThat.Enforcers.AnyArg.IsNotNull` it still displays at warning

**Comment by danielwertheim** [comment]
It's because the value (arg in your sample) is wrapped in a type `Param` and then passed to the enforcer. Don't really think we can fix this. Perhaps use one of the other styles that works:

- `EnsureArg.IsNotNull(i);`
- `Ensure.Any.IsNotNull(i);`

@ndrwrbgs do you have any ideas on this?

**Comment by dmarciano** [comment]
@rsobon I know it is not perfect, but have you tried configurating the null check validation methods in the .editorconfig file as mentioned here: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019#configurability

**Comment by ndrwrbgs** [comment]
Within the Param{T} I think that's the best we can get. We have annotations to tell R#, and could add ContractAnnotations, but CA1062 isn't smart enough to process any of those.

Brief brainstorming, I think we could do would be a major refactor that moves .Name and .OptsFn into _each_ of the validation methods e.g.
value.EnsureNotNull(), but that would be deviating from the existing design just to work around lacking features in CA so I would rather push on them to give us some contract mechanism to note that the value isn't null.

Other brief brainstorming - we'd have to return a new type `NotNullParam` from methods that are validating not null and let CA know that that struct's Value can never be null, and the user would have to do something like
```C#
string myInputString,

myInputString = Ensure.That(myInputString).IsNotNull().Value
```
which, again, looks super gross :(

**Comment by ndrwrbgs** [comment]
Oh, but @danielwertheim your suggestion was actually spot on. Those overloads would avoid the problem for folks who need to. I think the implementation of CA1062 (last I checked) was doing a very shallow analysis, so anything at all wrapped up in a type couldn't be noted.

**Comment by danielwertheim** [comment]
I think that since there are working alternatives in the lib (other API styles), no redesign should be made and I will close this one for now.

Feel free to reopen if I have missed anything.
