### ISSUE TITLE
ReadOnlySpan<char>

### ISSUE THREAD

**Issue by danielwertheim** [danielwertheim/Ensure.That#127]
For string validation purposes.

**Comment by ndrwrbgs** [comment]
Primary questions I'd have are
- [ ] Does `ReadOnlySpan` provide a better/more-interoperable API (are there times a user would have `ReadOnlySpan` but not `string`?
- [ ] Should we provide both, or just `ReadOnlySpan`?

If we keep both
- [ ] Can call sites interop okay (or will it be like "unsure which method to call")?

If we switch to only providing `ReadOnlySpan`
- [ ] Are there performance benefits in the operations we do on `string` that `ReadOnlySpan` will help with?
- [ ] Does the cost of turning a string into a `ReadOnlySpan` to call us, and converting back to string (to return the value) outweigh those benefits?

**Comment by ndrwrbgs** [comment]
It looks like mostly we're doing nullability & length. I ran some very rough benchmarks and length doesn't seem to perform valuably faster on ReadOnlySpan than on string, and there _is_ an overhead involved in casting to ReadOnlySpan (albeit minor) so I wouldn't replace string with it. But it does appear to be able to live side-by-side (at least for netcore30)
