### ISSUE TITLE
Ship-plan v9?

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#128]
@danielwertheim I was wondering what's on your roadmap before shipping version 9, hoping to get the `readonly structs` stuff for consumption and willing to help out with other changes you want to get in

**Comment by danielwertheim** [comment]
There's no roadmap. Features are added as needed. I'll rather do 100 releases with one feature than one with 10 features.

**Comment by ndrwrbgs** [comment]
Could we do a ship them to get the read-only structs out? :)

**Comment by ndrwrbgs** [comment]
Now I have a desire for the enum tests too :-P any sign of shipping?

**Comment by danielwertheim** [comment]
Noticed that parts of the message construct came in in the last PR but don't believe it's braking. So we can ship whenever.

**Comment by danielwertheim** [comment]
Shipping https://dev.azure.com/danielwertheim/ensure.that/_build/results?buildId=552&view=results

**Comment by danielwertheim** [comment]
Now, what's breaking that you want in v9

**Comment by ndrwrbgs** [comment]
Oh I wasn't wanting something specific, just wanted the new changes shipped
(v9 I just meant next version) :)
