### ISSUE TITLE
Add API-test to ensure all three APIs have parity, to make contribution easier

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#130]
#Reflection

**Comment by danielwertheim** [comment]
Do you have some sample code on what you had in mind?

**Comment by ndrwrbgs** [comment]
I'll handle it, feel free to assign to me it was mostly a note-to-self :)

**Comment by ndrwrbgs** [comment]
I will struggle with this though, if the APIs do not have matching names (like proposed in #131)

**Comment by danielwertheim** [comment]
They will not have matching API names in all cases. I was more interested in seeing what you had in mind to see what problem it solves and how it will be to maintain.

**Comment by ndrwrbgs** [comment]
https://github.com/ndrwrbgs/Ensure.That/tree/reflectionIsGross
