### ISSUE TITLE
Breaking change from 8.1.2 to 8.2.0

### ISSUE THREAD

**Issue by barakakha** [danielwertheim/Ensure.That#136]
i got this error after upgrading from 8.1.2 to 8.2.0
![image](https://user-images.githubusercontent.com/19611912/80084274-530d7680-855f-11ea-8637-160aa930f37e.png) 

this error was raised when trying to use version 8.2.0 with other nuget that was already compiled with version 8.1.2.  to be more clear 
Project A (with 8.2.0) ---> Nuget X ---> Ensure.That.8.1.2

**Comment by danielwertheim** [comment]
Yes, you are correct. Mistake. I'm not keen on reverting that PR.

What do you think about putting out a new package as v9.0.0 and "unlist" 8.2.0?

**Comment by barakakha** [comment]
Sounds good

**Comment by danielwertheim** [comment]
Done. 8.2.0 has been marked as deprecated and points at 8.1.2 instead. And v9.0.0 has been released. Thanks for reporting.

**Comment by ndrwrbgs** [comment]
I do think we should consider releasing a minor version bump that reverts
it on the 8.* path. Having been on the receiving end of this kind of change
before, having a "latest" that fixes it helps if I consume a package that
consumed it but hasn't updated to latest or rolled back.

I guess concern is alleviated if we have a way to see on nuget if any
packages are saying >=8.2.0
