### ISSUE TITLE
Add the ability to check that a string is made up of a certain type of character(s)

### ISSUE THREAD

**Issue by LiquidPT** [danielwertheim/Ensure.That#141]
I have a need to test whether a string (and possibly just a char) are of a certain type: Letter, Digit, LetterOrDigit, etc. I was in the process of converting my argument checking over to Ensure.That and found that (I think) it doesn't exist. I have it checked similar to this now:

            if (!argString.All(char.IsLetterOrDigit))
            {
                throw new ArgumentOutOfRangeException(nameof(argString), "Expecting only letters and digits");
            }

I realize that I could use a Regex for this, but this seems simpler.

**Comment by ndrwrbgs** [comment]
This should handle that, right?
https://github.com/danielwertheim/Ensure.That/blob/45a9180b4a6c4d64d70a1b2e0feeb5dc2a2904f4/src/projects/EnsureThat/EnsureThatStringExtensions.cs#L27

**Comment by LiquidPT** [comment]
As I said above, I realize it could be done in Regex. I just don't know any dev that likes Regex and it seemed like this simple cases maybe should be included.

I don't know if the implementation I have above or a facade over the Regex method is better (easier to read, more performant, etc). There were a few reasons for my posting the issue:

1. To make sure I hadn't completely missed an existing implementation
2. To see if this is something that would be of interest to add to the library
3. To discuss possible implementations

I'm perfectly willing to go implement (and likely will as an extension in my project if it's not appropriate here)

**Comment by danielwertheim** [comment]
Why not add a member in for this against strings? `IsAllLettersOrDigits`

**Comment by pBouillon** [comment]
Hi ! Is this issue up for grabs ?  
I would like to work on it and suggest a PR according to the method you suggested @danielwertheim 😄
