### ISSUE TITLE
Couldn't find file or assembly

### ISSUE THREAD

**Issue by endikamontejo** [danielwertheim/Ensure.That#15]
Hi!
I am getting the following error: "Could not load file or assembly 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=xxxxxxx' or one of its dependencies. The system cannot find the file specified" when calling to the constructor of MyCouch's MyCouchUriBuilder constructor.

Also I want to comment that in order to sign our project's installer, we sign MyCouch package with the package StrongNaming https://www.nuget.org/packages/Nivot.StrongNaming/

**Comment by danielwertheim** [comment]
Don't see how this is an issue with Ensure.That? Open issue in MyCouch if something does not work with MyCouch.
