### ISSUE TITLE
vNext

### ISSUE THREAD

**Issue by danielwertheim** [danielwertheim/Ensure.That#16]
Oh dear

**Comment by danielwertheim** [comment]
After wrestling with possible solutions:

(1): Replace PCL with vNext class lib. Target: dotnet, netcore451, net45
(2): Add shared lib. Move code there. Add yet another PCL that supports 4.6 and asp.net 5. Ref the shared lib from the two PCLs.

**Comment by damianh** [comment]
Ensure.That 3.1.0 is broken. Installing it into a .net 4.5.1 project adds a reference to EnsureThat.vNext.dll which is compiled against .net 4.6 and references a later system.runtim (4.0.20).

Also, I don't think the dll names need to change.

**Comment by danielwertheim** [comment]
Thanks. You could try and clone and update the nuspec and run deployscript
and try a local package and see if that works.

Why does dlls need to be renamed?

**Comment by danielwertheim** [comment]
@damianh `v3.1.1` should resolve the correct one.

**Comment by damianh** [comment]
I just reverted to 2.0.0.

The DLL suffixes ".dinosaur" and ".vnext" are not necessary. The original
name would be fine.

**Comment by danielwertheim** [comment]
@damianh it's an "easy" way for "me" to quickly see which one has been picked. But yes. It's not needed but nor is it a harm, apart from ugly names perhaps, no?

**Comment by damianh** [comment]
There's no harm, it's just not idiomatic.

**Comment by adriaanp** [comment]
There is harm in dnx can't do assembly redirection from assembly that references 2.0.0 and your project references 3.2.0 for example.

Reason why I can't use MyCouch as is.
