### ISSUE TITLE
Change InvokerParameterNameAttribute to CallerMemberNameAttribute

### ISSUE THREAD

**Issue by r-pankevicius** [danielwertheim/Ensure.That#178]
Could you change JetBrains.Annotations.InvokerParameterNameAttribute to [System.Runtime.CompilerServices.CallerMemberNameAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute)?

I'm forced to use old style `EnsureArg.IsNotNull(notNullString, nameof(notNullString));` syntax, explicitly giving parameter name instead of simple `EnsureArg.IsNotNull(notNullString);`.

Here are [2 example tests](https://github.com/r-pankevicius/Ensure.That/commit/9baa20587607a2e6404fcd265d69c7f3c0451ec6) showing the difference.

**Comment by ndrwrbgs** [comment]
Would not CallerMemberName give the name of the method, rather than the
name of the method parameter passed to the ensure method?

**Comment by r-pankevicius** [comment]
@ndrwrbgs Yes, you are right. It yields name of the calling method. And it even discards local methods:
https://github.com/r-pankevicius/Ensure.That/commit/5f8b401df7571f1f66e08104329f537666de7b3e

**Comment by r-pankevicius** [comment]
Will close this issue: CallerMemberNameAttribute is not suitable here.

But before I have a question: what does JetBrains.Annotations.InvokerParameterNameAttribute do?
Does it work in JetBrains Rider IDE?
