### ISSUE TITLE
Referenced assembly System.Linq.Expressions cannot resolve in dnx46

### ISSUE THREAD

**Issue by smokedlinq** [danielwertheim/Ensure.That#21]
Trying to include Ensure.That in a ASP.NET 5 / dnx46 project and receiving the following error about a missing assembly reference:

Error	 CS0012 The type 'Expression<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Linq.Expressions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I am added the System.Linq.Expressions nugget package for the most recent (beta) version as well as the 4.0.10.0 version but that doesn't resolve the build error.

**Comment by danielwertheim** [comment]
Include as source package or as compiled resource?

**Comment by adweigert** [comment]
Compiled

**Comment by danielwertheim** [comment]
There's a new release coming that has ditched the PCL's completely, now composed as DotNetCore lib instead. The conversion is done. Just adding some new features. Work is being done in this branch: https://github.com/danielwertheim/Ensure.That/tree/dotnetcore
