### ISSUE TITLE
Suggestion: add WithException

### ISSUE THREAD

**Issue by iamgurdip** [danielwertheim/Ensure.That#23]
Please add an extension method WithException(...) to define a custom exception to be thrown. It can be done today with Throws => Throws(x => x.Custom( ....)) but seems a little lengthy and not as fluent.

Thank you.

**Comment by danielwertheim** [comment]
Forgot to close with the commit https://github.com/danielwertheim/Ensure.That/commit/5108a7d142183b06f59c4c0fb4007169a815a3fa

**Comment by iamgurdip** [comment]
Thank you so much.

**Comment by danielwertheim** [comment]
Haven't uploaded the beta nuget yet. Hopefully within a couple of hours.
