### ISSUE TITLE
Add support for IEnumerable<T>

### ISSUE THREAD

**Issue by wgv-sethlivingston** [danielwertheim/Ensure.That#26]
The library appears to support IList<T>, ICollection<T>, and arrays, but IEnumerable<T> should cover all of those bases, shouldn't it? Most of the collections I deal with are IEnumerable<T>.

Great library!

**Comment by danielwertheim** [comment]
It has been like that to reduce the risk that someone passes something that is deferred. But sure. Why not.

**Comment by danielwertheim** [comment]
Sticking to not switching to IEnumberable for not exposing an API where people can pass something that is deferred. If it becomes a maintenance issue it might change in the future.

**Comment by ndrwrbgs** [comment]
@wgv-sethlivingston the NoNull will work with IEnumerable still. Should you need the other utilities like HasAny which will force enumeration, it’s best to ensure enumeration only happens once. In those cases, prefer code like follows:

```
void DoCoolStuff(IEnumerable<int> input)
{
  // pre-processing
  IList<int> enumeratedInput = input as IList<int> ?? input.ToList();
  
  EnsureArg.SizeIs(enumeratedInput, 15, nameof(input));
}
```

(Also if you’re always handling IEnumerables be careful of the cost of multiple enumeration, which can be costly even if the enumerables are not deferred. E.g. if you pass an IEnumerable to two different methods, you’ll have to make sure those methods don’t both individually enumerate it. In such cases, use the trick demonstrated above to ensure single enumeration)

**Comment by ndrwrbgs** [comment]
@danielwertheim, should this get raised again in the future one work around (beyond the Resharper context hint of [InstantHandle], which helps but only for users of Reshaper), one possibility would be to accept IEnumerable<T> but only as a ref parameter, returning an IList<T> to make it clear it’s enumerated, and replacing the input IEnumerable<T> with the single-enumerated list (or a Memoized IEnumerable).

That said, this is only an option and given that it starts to violate DRY I’d recommend instead that if support is _absolutely necessary_ an “extension library” separately released from this one expose the functionality.

**Comment by ndrwrbgs** [comment]
*SRP (single responsibility, not DRY oops)

**Comment by danielwertheim** [comment]
This will be supported with PR #77 via `Ensure.Enumerables`
