### ISSUE TITLE
Sign assemblies with a Strong Name

### ISSUE THREAD

**Issue by RomanDidenko** [danielwertheim/Ensure.That#27]
May we have output assemblies signed with a Strong Name?

https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx

**Comment by tsvetelin-pavlov** [comment]
+ 1
Please!

**Comment by danielwertheim** [comment]
What if there was an updated source package instead that you then could install as source in your own assemblies?

**Comment by tsvetelin-pavlov** [comment]
Does it mean that the whole code base of EnsureThat will be copied in my project?
If yes, that most certainly I will not use it...

**Comment by DanAvni** [comment]
It has been a year since this was requested. Any chance the assembly will be signed?

**Comment by wardboumans** [comment]
I would like to see this as well, running in to assembly loading issues.

**Comment by tsvetelin-pavlov** [comment]
I really don't get the fuzz and the discussions and the whole wondering about strong naming an assembly - it is a matter of minutes to generate the key (a self-signed one). I guess nobody here needs a strong name with a key, signed from authority, but even if someone does, it can be done in hours and it is not-that-expensive - they are free authorities after all...

**Comment by wardboumans** [comment]
@tsvetelin-pavlov I know I can selfsign (im not asking for authority signed either). But what good is nuget when I still need to sign the assembly?

**Comment by tsvetelin-pavlov** [comment]
Totaly agree! 
I am not attacking anybody with my previous comment (I hope @wardboumans didn't felt accused of smth) - I mean - it is easy, it is literally effortless to strong-name that assembly, and it is well-known good practice for years. And yet, there are many projects that owners just were not doing it! And there are discussions, threads, issues - you named it - where people ask for a simple, strong name and there are still not one. This project is one of them.
So in this cases, I need to download the source, put it in our internal repo, sign it and produce the packages by myself, then upload it to our internal package feed. And simply making strong named assembly could spare all of this.

**Comment by danielwertheim** [comment]
If this is done it would merely be for identification purposes of the assembly and for simplicity the key would then  be included in the repo. @DanAvni not sure what the auditors ensuring you follow the regulations e.g. would think of that as it means anyone can clone and self sign it and....

But sure... A PR that solves this issue using the build script (Cakebuild) as a separate task "Sign" that signs the assemblies before producing the package. Not sure what the preferred way of signing an assembly with Cake is.

**Comment by DanAvni** [comment]
@danielwertheim , Totally true that the snk is in the project and is open to all. The sad part is that I must comply and on the other side the party that made me comply does not check anything. But if there was a violation of my compliance at some point then I would be to blame... Sad but true
