### ISSUE TITLE
English typo

### ISSUE THREAD

**Issue by bandolir** [danielwertheim/Ensure.That#28]
cannot instead of can not
public static string Common_IsNotNull_Failed { get; private set; } = "Value can not be null.";

**Comment by danielwertheim** [comment]
Isn't both OK? http://www.write.com/writing-guides/general-writing/word-choice/cannot-versus-can-not/

**Comment by bandolir** [comment]
https://en.oxforddictionaries.com/usage/cannot-or-can-not

**Comment by danielwertheim** [comment]
Not that I think someone has built anything that takes a dependency on a message, but since it's still a valid message I'll not change.
