### ISSUE TITLE
do not allow us to be an idiot

### ISSUE THREAD

**Issue by bandolir** [danielwertheim/Ensure.That#29]
would be good if you don't let us to do the following
Ensure
    .That(myString, nameof(myString))
    .IsNotNullOrWhiteSpace()
    .WithExtraMessageOf(p => "Some more details");

**Comment by danielwertheim** [comment]
Agree, but not sure I want to introduce a breaking change and have the end-methods stop returning `Param<T>`.

**Comment by bandolir** [comment]
keep this version and introduce v2 :)

**Comment by bandolir** [comment]
btw you should think about support of code contracts
https://msdn.microsoft.com/en-us/library/dd264808(v=vs.110).aspx

**Comment by danielwertheim** [comment]
Or people can just use code contracts?

**Comment by bandolir** [comment]
preconditions section
if ( x == null ) throw new ...  
Contract.EndContractBlock(); // All previous "if" checks are preconditions  
before the endcontractblock the users cannot use your library for argument validation.

**Comment by danielwertheim** [comment]
What change is it that you would like to see? How should it behave (the last one covered in this opened issue)

**Comment by bandolir** [comment]
I've just glanced on your code. 
In fact I don't use your library just one of the intern wanted to use it on my project and I didn't let him. Sorry about that. 
I've managed the validation with custom code snippets.

**Comment by danielwertheim** [comment]
Redid the chaining.
