### ISSUE TITLE
Ensure.That().Value?

### ISSUE THREAD

**Issue by thnk2wn** [danielwertheim/Ensure.That#38]
Was .Value removed due to some .NET standard limitation? Any plans to bring it back (i.e. net std 2.0)?

It's a bummer this doesn't appear to work anymore as it was handy:

    _logger = Ensure.That(logger, nameof(logger)).IsNotNull().Value;

**Comment by danielwertheim** [comment]
It has to do with the first comments here: https://github.com/danielwertheim/Ensure.That/issues/29

**Comment by thnk2wn** [comment]
Ahh. Personally I'd prefer the tradeoff of having the value of Param<T> over some combinations it might provide that might be invalid. This doubles the amount of code to be written in our ctors.

Or maybe there's some hybrid approach compromise.

**Comment by danielwertheim** [comment]
What if the other variation of the API returned the value:

```csharp
_logger = EnsureArg.IsNotNull(logger, nameof(logger));
```

**Comment by thnk2wn** [comment]
@danielwertheim Yeah, that'd work for me!
