### ISSUE TITLE
Consider replacing string.Empty.Equals(value)

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#47]
I notice new changes in the library around performance (specifically, the migration away from `Ensure.That` to static methods and `EnsureArg`). Given performance is important -- let's replace string.Empty.Equals(value) with `value != null && string.IsNullOrEmpty(value)`

BenchmarkDotNet micro benchmark showed this to be ~3x faster (intuitively makes sense as it doesn't have to deal with the overhead of equality just to see if it's empty - which I think the BCL uses `.Length` to test)

**Comment by danielwertheim** [comment]
Thanks. Reviewed and believe it could be simplified.

**Comment by danielwertheim** [comment]
Forgot to comment that PR closes this.
