### ISSUE TITLE
Design: Why does SizeIs accept a long count since collection.Count is an int?

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#49]
Was it a some performance concern to keep just int?

Though here's a sample that would require a `long`, via `Enumerable.LongCount` perhaps, but I imagine it is only applicable in contrived scenarios and not applicable on `ICollection` which exposes an `int` `Count` property, nor on `IList` which exposes an `int` `this[]` accessor.

```
var myBigEnumerable = Enumerable.Range(0, int.MaxValue)
  .Concat(Enumerable.Range(0, 10));
Ensure.Collection.SizeIs(
  myBigEnumerable,
  2147483657,
  "paramName");
```

**Comment by danielwertheim** [comment]
Good Q, but I do think it was convenience to not have to invoke the ensure with `(int)myLong`

What's funnier though (just noticed) is the array version... it does not use `LongLength` for that overload.

**Comment by ndrwrbgs** [comment]
Woah, I didn't even know `LongLength` was a thing. I guess we really do have lots of memory these days! I hope not many people are using this, sad LOH allocations 😞.

What would you like to see here?
- Obviously we can update the array version to `LongLength` (given the next few items)
- Should an IEnumerable version be exposed? (with comment & [InstantHandle] annotation to signal that it will actually enumerate it - unless )
  - I'd personally recommend not doing this because it's unlikely IMO that a user actually wants to enumerate such a sequence, especially more than once
  - Array seems to be the only exposed way of getting a long count in O(1) time in the current BCL, unless I am missing something
- Should we continue to expose a `long` version?
  - I'd tentatively say yes after further thinking, but wanteto make sure there is a discussion/thought here. See example below.

```
// Example supporting the long version
void Example()
{
    var collection = new[] { 1, 2 };
    
    Console.WriteLine("How many items do you demand to have in the collection?");
    long input = long.Parse(Console.ReadLine());
    
    // Here we have 1 of 3 behaviors
    // Option 1: we throw ArgumentOutOfRangeException
    // Option 2 (they have to cast): if they are unchecked{} - they get off values like wrapping around if the input is in the > int.MaxValue
    // Option 3 (they have to cast): if they are checked{} - they get an OverflowException
    Ensure.That(collection).SizeIs(input);
}
```

**Comment by ndrwrbgs** [comment]
So my suggestion would be to correct the Array version, leave the long version, and omit adding an IEnumerable version (e.g. make sure all exposed versions right now won't accept IEnumerable but only ICollection/IList)

**Comment by danielwertheim** [comment]
Good morning. I agree to the last comment. IEnumerable overloads should not be added even if attributes can help with discoverability. Keep the long for convenience and correct array.
