### ISSUE TITLE
Design: Why is there a specific T[] overload when T[] : ICollection<T>, IList<T>?

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#52]
Was this performance based also or some other scenario? More of a question than issue 😄.
Thank you for your patience and explanations!

**Comment by danielwertheim** [comment]
Ultimately one would like to use `IEnumerable` and `IEnumerable<T>`, how-ever, I didn't want the risk that someone passes anything that is "deferred" and thereby potentially evaluated more than once.

And at one point when building this, there was some case like, having an `IList<T> value` and wanting to invoke an Ensure method for it that accepts `ICollection<T>` without user having to cast.

Do you have a sample showing the change you would like to see?

**Comment by ndrwrbgs** [comment]
Hey @danielwertheim, the suggestion would have been to remove the T[] overloads, since this works:

```
void Main()
{
	ICollection<string> s1 = new string[] { };
	IList<string> s2 = new string[] { };
	string[] s3 = new string[] { };

	Sample(s1);
	Sample(s2);
	Sample(s3);
}

void Sample<T>(ICollection<T> source) { }
//void Sample<T>(IList<T> source) {}
//void Sample<T>(T[] source) {}
```

However given my recent leanings around how the runtime works, probably do not want to do this. The reason being that I believe T[] is handled specially for cases like Enumeration, and I think the boxing into its interface takes more time for Length even.

From BenchmarkDotNet:

## Enumeration ##
[EnumerationCode.txt](https://github.com/danielwertheim/Ensure.That/files/1468967/EnumerationCode.txt)

- Renamed from the code for mental processing ease
  - AllowsArrayWithCollection -> Collection as Collection
  - AllowsArrayWithArray -> Array as Array
  - AlwaysCollectionWithCollection -> Collection as Collection (2)
  - AlwaysCollectionWithArray -> Array as Collection

|                        Method | CollectionSize |         Mean |      Error |     StdDev |       Median |  Gen 0 | Allocated |
|--- |--- |---:|---:|---:|---:|---:|---:|
|       Collection&#160;as&#160;Collection |              0 |    38.749&#160;ns |  0.8054&#160;ns |  1.7510&#160;ns |    37.954&#160;ns | 0.0057 |      24 B |
|                 Array&#160;as&#160;Array |              0 |     1.805&#160;ns |  0.0762&#160;ns |  0.0907&#160;ns |     1.802&#160;ns |      - |       0 B |
|   Collection&#160;as&#160;Collection&#160;(2) |              0 |    37.424&#160;ns |  0.2164&#160;ns |  0.1565&#160;ns |    37.419&#160;ns | 0.0057 |      24 B |
|            Array&#160;as&#160;Collection |              0 |    25.528&#160;ns |  0.3963&#160;ns |  0.3707&#160;ns |    25.498&#160;ns |      - |       0 B |
|       Collection&#160;as&#160;Collection |             10 |   148.225&#160;ns |  0.8985&#160;ns |  0.8405&#160;ns |   148.196&#160;ns | 0.0055 |      24 B |
|                 Array&#160;as&#160;Array |             10 |     5.105&#160;ns |  0.1395&#160;ns |  0.1764&#160;ns |     5.066&#160;ns |      - |       0 B |
|   Collection&#160;as&#160;Collection&#160;(2) |             10 |   150.689&#160;ns |  1.3626&#160;ns |  1.2746&#160;ns |   150.759&#160;ns | 0.0055 |      24 B |
|            Array&#160;as&#160;Collection |             10 |    87.040&#160;ns |  1.0284&#160;ns |  0.8588&#160;ns |    86.972&#160;ns | 0.0046 |      20 B |
|       Collection&#160;as&#160;Collection |            100 | 1,007.755&#160;ns |  8.7992&#160;ns |  8.2308&#160;ns | 1,009.627&#160;ns | 0.0038 |      24 B |
|                 Array&#160;as&#160;Array |            100 |    53.533&#160;ns |  0.9138&#160;ns |  0.8101&#160;ns |    53.429&#160;ns |      - |       0 B |
|   Collection&#160;as&#160;Collection&#160;(2) |            100 | 1,038.829&#160;ns | 22.3762&#160;ns | 47.1990&#160;ns | 1,023.280&#160;ns | 0.0038 |      24 B |
|            Array&#160;as&#160;Collection |            100 |   641.222&#160;ns | 11.8554&#160;ns | 11.0896&#160;ns |   636.922&#160;ns | 0.0038 |      20 B |

## Length/Count ##
[CountsCode.txt](https://github.com/danielwertheim/Ensure.That/files/1468966/CountsCode.txt)

|                         Method | CollectionSize |      Mean |     Error |    StdDev | Allocated |
| --- |--- |---:|---:|---:|---:|
|AllowsArrayWithCollection |              0 | 1.8141&#160;ns | 0.0472&#160;ns | 0.0418&#160;ns |       0 B |
|AllowsArrayWithArray |              0 | 0.0154&#160;ns | 0.0280&#160;ns | 0.0248&#160;ns |       0 B |
|AlwaysCollectionWithCollection |              0 | 1.8169&#160;ns | 0.0677&#160;ns | 0.0633&#160;ns |       0 B |
|AlwaysCollectionWithArray |              0 | 2.8089&#160;ns | 0.0851&#160;ns | 0.0796&#160;ns |       0 B |
|AllowsArrayWithCollection |             10 | 1.8087&#160;ns | 0.0759&#160;ns | 0.0986&#160;ns |       0 B |
|AllowsArrayWithArray |             10 | 0.0185&#160;ns | 0.0284&#160;ns | 0.0252&#160;ns |       0 B |
|AlwaysCollectionWithCollection |             10 | 1.8854&#160;ns | 0.0570&#160;ns | 0.0533&#160;ns |       0 B |
|AlwaysCollectionWithArray |             10 | 2.9221&#160;ns | 0.0981&#160;ns | 0.1719&#160;ns |       0 B |
|AllowsArrayWithCollection |            100 | 1.8198&#160;ns | 0.0472&#160;ns | 0.0441&#160;ns |       0 B |
|AllowsArrayWithArray |            100 | 0.0129&#160;ns | 0.0215&#160;ns | 0.0190&#160;ns |       0 B |
|AlwaysCollectionWithCollection |            100 | 1.9146&#160;ns | 0.0958&#160;ns | 0.1404&#160;ns |       0 B |
|AlwaysCollectionWithArray |            100 | 2.8034&#160;ns | 0.0962&#160;ns | 0.1145&#160;ns |       0 B |

**Comment by danielwertheim** [comment]
Thorough investigation. Great work.
