### ISSUE TITLE
Consider MethodImpl(MethodImplOptions.AggressiveInlining) on methods (specifically .That)

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#54]
A quick pass with BenchmarkDotNet (I'm no expert though!)'s Jit Diagnoser suggested that the .That methods were unable to be inlined because their estimated size were too large. Argument validation is likely valid/desirable to inline, and addition of the attribute may assist.

**Comment by danielwertheim** [comment]
@ndrwrbgs  Since the `Ensure.That` flavor is going in next major, this is not an issue, right?

**Comment by ndrwrbgs** [comment]
I’d have to check again if we want data to back up the decision, but I’d imagine it may still be good to inline argument checking.

**Comment by danielwertheim** [comment]
Closing for now.
