### ISSUE TITLE
Allow for choosing exception type

### ISSUE THREAD

**Issue by LittleUmbrella** [danielwertheim/Ensure.That#7]
"Ensuring that..." (i.e. the concept) applies to more than just arguments.  I'm thinking specifically about state.  For instance, I'd like to ensure that HttpContext.Current is not null, but I don't want to throw an argument exception if it is.  I'd want to throw an InvalidOperationException.  I'd suggest

```c#
public static class CustomExceptionExtensions
    {
        public static Param<T> WithExceptionOf<T>(this Param<T> param, Func<T> exceptionFn)
        {
            param.ExceptionFn = messageFn;
            return param;
        }
    }
```

either that or add `.State` after `Ensure.That()` or something to cue the library to throw InvalidOperationException.

**Comment by ashutoshraina** [comment]
Hi,
Are there any plans to get this feature in ? Would love to have this :+1:

**Comment by danielwertheim** [comment]
Any other suggestions of how it should look, seen to API, other than the above?

**Comment by ashutoshraina** [comment]
```
Ensure.That(HttpContext.Current).IsNotNull(throw => throw.InvalidOperation);
```
Yup, I think that should do it.

or 

```
Ensure.That(HttpContext.Current).IsNotNull().Raise(ex => new MyCustomException());
```

**Comment by danielwertheim** [comment]
Sample usage can bee seen here: https://github.com/danielwertheim/Ensure.That/commit/a42c213eac481676a869a3ac3f9a5c96aeaf4867#diff-b9376b431e345afb36ba68af5d8d23acR43

And for completely custom exceptions:
https://github.com/danielwertheim/Ensure.That/commit/a42c213eac481676a869a3ac3f9a5c96aeaf4867#diff-b9376b431e345afb36ba68af5d8d23acR55

Opinions?

**Comment by ashutoshraina** [comment]
LGTM..but would like to see others weigh in as well

**Comment by LittleUmbrella** [comment]
Yeah, that's just what I wanted two years ago, I think.

**Comment by danielwertheim** [comment]
Yes it says two years ago, I'm fully aware of that. Didn't want it in before as it has been more for argument validation.

**Comment by LittleUmbrella** [comment]
no worries.  I was just giving you a hard time.  If I wanted it badly enough, I would have just forked and added it.  

I closed it because I felt you implemented the feature as proposed.  didn't see that it was not in the master branch yet.  my bad.  I'm fine keeping this open until/if this gets into the master branch.
