### ISSUE TITLE
Consider [Conditional] instead of/in addition to On/Off

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#70]
```
[DebuggerStepThrough]
[Conditional("notsatisfied")]
public static void AnyConditional<T>(this Param<IList<T>> param, Func<T, bool> predicate)
```

Results in 
![conditional](https://user-images.githubusercontent.com/10776890/32808754-0ac0a480-c949-11e7-820c-fdfd6c0f5962.PNG)

and benchmark confirms that even the `That` is not run
![benchmark](https://user-images.githubusercontent.com/10776890/32808782-1c031d9a-c949-11e7-980f-adeb16a1b3d3.PNG)

This change would prevent the overhead (though minimal) of checking `IsActive` ever, but would make Active/Inactive toggleable at the binary level only rather than dynamically at runtime (is dynamic a user requirement? I'm not sure of the uses cases for it)

Benchmark code:
```
private IList<string> strings;

public ArgumentValidation()
{
    this.strings = new List<string>(10);
    for (int i = 0; i < 9; i++)
    {
        this.strings.Add(string.Empty);
    }
    this.strings.Add(null);
}

[Benchmark]
public void AnyNoThrow()
{
    try
    {
        Ensure.That(this.strings).Any(s => null == (s));
    }
    catch { }
}

[Benchmark]
public void AnyConditional()
{
    Ensure.That(this.strings).AnyConditional(s => !string.IsNullOrEmpty(s));
}

[Benchmark]
public void BCLNoThrow()
{
    var len = this.strings.Count;
    for (int i = 0; i < len; i++)
    {
        if (null == (this.strings[i]))
        {
            return;
        }
    }
    try {
    throw new Exception();
    }
    catch { }
}

[Benchmark]
public void Baseline()
{
    Ensure.That(this.strings);
}
```

**Comment by ndrwrbgs** [comment]
Above used struct `Param<T>`. Below uses class

|         Method |      Mean |     Error |    StdDev |
|--------------- |----------:|----------:|----------:|
| AnyConditional | 0.0074 ns | 0.0101 ns | 0.0108 ns |
|       Baseline | 6.4007 ns | 0.1643 ns | 0.4765 ns |

**Comment by danielwertheim** [comment]
But that would mean that all public endpoints that today return the value would need to either stop returning the value or have a new version as the `Conditional` attribute only works on `void` members.

Adding new members that are `void` is not an option as that will pollute the API. Then we are down to stop returning the values. Me myself don't use the returned value, but others have asked for it.

Then we are down to.... removing the check or replacing the check with pre-combile checks against a symbol, like `Conditional` would.

```csharp
#if ENSURE_THAT_DISABLED
  return; //or return value;
#endif
```

**Comment by danielwertheim** [comment]
Can be done after #78

**Comment by danielwertheim** [comment]
@ndrwrbgs `Conditional` does not support negations so it has to be something like:

```
[Conditional("EnsureThatIsEnabled")]
```

but can't really expect users to have to define that. What's your idea on this?

**Comment by ndrwrbgs** [comment]
Sigh, should've looked into this more before.
The only thing I can think of is to offer a copy of the APIs that is gated behind the conditional, I also don't think users should _have_ to define something to make it work.

I think such a wrapper would quite likely not belong _inside_ this library, though it's up to you if you want to expose ConditionalEnsures.

If we back out of this change, would we keep #78 do you think?

**Comment by danielwertheim** [comment]
As `ConditionalAttribute` does not support `NOT` and as there are no workarounds for third party libs, this can not be implemented.
