### ISSUE TITLE
Custom exception error with EnsureArgs

### ISSUE THREAD

**Issue by xigolle** [danielwertheim/Ensure.That#75]
Dear, 

I am trying to use your library but I see that Ensure.That is going to be deprecated. 
So I was curious on how I can do the following:
`EnsureArg.IsFalse(true);` 

And have my own exception stating something like "value should be not true".
Hope you can help me out because I could not find it in the docs.

**Comment by xigolle** [comment]
Hi ndrwrbgs,

Well now when ensureThat throws an error if something is null it is just a generic message like value cannot be null. 
But it would be nice if we could set a more custom message so we can inform the user better on what is happening.

**Comment by danielwertheim** [comment]
Some options comes to my mind (note, not saying anything is correct)

- We keep the `Ensure.That` (sigh... never ending story)
- We see this library as a guard clause lib for enforcing contracts, not a validation for end user.... and then skip support for custom messages
- We add an optional argument `(param, opts) => opts.CustomMessage($"This value {param} is no good")`

**Comment by xigolle** [comment]
To be honest I really like the last idea. That way you can still use the lib as a guard clause but leave it open for additional messages.

**Comment by danielwertheim** [comment]
Decision is to add something like:

```
(param, opts) => opts.CustomMessage($"This value {param} is no good")
```

**Note**. It should be possible to (later on) extend this with something like:

```
(param, opts) => opts.CustomException($"This value {param} is no good")
```

**Comment by ndrwrbgs** [comment]
What’s the expected type of opts here?

**Comment by danielwertheim** [comment]
I will call it `EnsureOptions`

**Comment by ndrwrbgs** [comment]
:smiley: I meant what’s it’s purpose. To encapsulate the input arguments?

**Comment by danielwertheim** [comment]
Nope. To contain optional customizations of the exception or message:

```csharp
EnsureArg.IsTrue(true, "myParam", o => o.WithMessage("asdf"));
```

or

```csharp
EnsureArg.IsTrue(true, "myParam", o => o.WithException(new FooException("Schnitzel!"));
```

The latter takes precedence.

**Comment by danielwertheim** [comment]
Something like this: https://github.com/danielwertheim/Ensure.That/commit/1b6411c794ec12141a95cee26cd3efc2e1a7a773

Will probably add `WithExtraMessage` to ease migration from obsolete `Ensure.That`
