### ISSUE TITLE
Consider more specific exceptions for validation methods

### ISSUE THREAD

**Issue by ndrwrbgs** [danielwertheim/Ensure.That#76]
E.g. ArgumentNotLessThanException with fields that expose the actual value and the validated against value.

**Comment by ndrwrbgs** [comment]
v8 Breaking change

**Comment by ndrwrbgs** [comment]
The benefit would be in providing more information upstream about the failure - most of the top nuget packages provide custom exception types since c# unlike java does not provide a super rich set of exceptions.

A couple uses I can see:
# customization of exception messages if they need to wrap the one thrown from here
# ease of structured logging, no string parsing to get the bounds needed
# in cases where the value is T (like Contains), a ToString() might not represent the value sufficiently (they’ll get “expected element List’1<System__Canon>” kind of messages that they aren’t able to rectify).

All in all these aren’t :vital: and are rather edge cases but if we are throwing anyway I’d rather take an “enterprise” style approach and support as many use cases as possible (where supporting those cases does not add substantial work at least)

**Comment by ndrwrbgs** [comment]
Uhhh, I fail at markdown and on mobile it isn’t letting me edit it :(
Those headers were supposed to be lists, apologies!

**Comment by danielwertheim** [comment]
`v8.0.0` is going out nowish, but this isn't really breaking as I see it as it would still be able to extend the current exceptions being thrown in the specific cases. If so, then it can be added whenever.

**Comment by ndrwrbgs** [comment]
Agreed I do not think it would be breaking (except if someone expected
EXACTLY that type of exception, in which case they were probably doing
silly things anyway :) )

**Comment by ndrwrbgs** [comment]
It looks like you were okay with the proposal above. I will consider this item unblocked (this is my non-committal way of saying I'll work on it)
