### ISSUE TITLE
EnsureArg Boolean ignores the optsFn

### ISSUE THREAD

**Issue by iamgurdip** [danielwertheim/Ensure.That#84]
EnsureArg.Booleans do not pass the OptsFn to the Ensure.Bool.IsTrue method. 
[https://github.com/danielwertheim/Ensure.That/blob/master/src/projects/EnsureThat/EnsureArg.Booleans.cs](url)

**Comment by danielwertheim** [comment]
Thanks! Fixed in 7.2.1 which has been released on NuGet.org: https://www.nuget.org/packages/Ensure.That/7.2.1

**Comment by iamgurdip** [comment]
Thanx for the fix so fast!
