### ISSUE TITLE
String.IsNotNullOrWhitespace Returning ArgumentNullExceptions for Whitespace Values

### ISSUE THREAD

**Issue by doctorhilarius** [danielwertheim/Ensure.That#87]
<package id="Ensure.That" version="7.2.1" targetFramework="net461" />

I have tons of unit tests in the same project verifying the arguments are valid throughout the project using Ensure.String.IsNotNullOrWhiteSpace(). They all expect an ArgumentNullException for null string values and an ArgumentException for empty or whitespace strings.

However, the empty/whitespace exceptions switch from ArgumentExceptions to ArgumentNullExceptions and back for no apparent reason. And when they switch, they are consistent within a class but not w/in the project. So 2 classes can use the exact same Ensure.String.IsNotNullOrWhitespace method for the exact same argument, but one class throws ArgumentExceptions and the other throws ArgumentNullExceptions.

In looking at the source code, this seems totally impossible; however, I can see the issue happening repeatedly. I haven't figured out how to intentionally cause the problem; however, that's to be expected b/c the behavior is clearly governed by something outside of my project b/c it switches w/out any changes to the project.

This is just a pain b/c a large number of unit tests start failing intermittently.

**Comment by ndrwrbgs** [comment]
Could you supply a repro for debugging?

**Comment by danielwertheim** [comment]
There's no shared state or anything so sounds weird that behavior switches.

Are you passing in a custom exception function?

**Comment by danielwertheim** [comment]
@doctorhilarius any more input on this?

Haven't seen any issue with this myself, nor have I heard anyone else.

**Comment by danielwertheim** [comment]
There are tests for this.

Current version: https://github.com/danielwertheim/Ensure.That/blob/master/src/tests/UnitTests/EnsureStringParamTests.cs#L81

Upcoming version: https://github.com/danielwertheim/Ensure.That/blob/feature-v8/src/tests/UnitTests/EnsureStringParamTests.cs#L81
