### ISSUE TITLE
Estimated release date for v8

### ISSUE THREAD

**Issue by TimSirmovics** [danielwertheim/Ensure.That#90]
Hi,

We are holding off upgrading most of our projects to v7 as v8 is coming soon and we would rather do a single upgrade.

Do you have a rough estimate of how long away v8 is?

**Comment by danielwertheim** [comment]
After this evening there seem to be only one item left: https://github.com/danielwertheim/Ensure.That/milestone/4

And given some opinions in #27 and the effort needed to make that happen...

**Comment by TimSirmovics** [comment]
Ah, I didn't realise I could view Milestone progress in GitHub.

Thanks for the update - hopefully we can see v8 soon.

**Comment by danielwertheim** [comment]
@TimSirmovics well... I was kind of hoping anyone in #27 that actually wants it would "step up"... I guess I'll have to do it but not today.
